import {
  IStateLanguage,
  IStatePages,
  IStatePosts,
  IStateProjects,
  IStateSetting,
  IStateSitewords,
  IStateCategories,
} from "./../interfaces/index";

export const lang: string = "en-gb";
export const langs: IStateLanguage[] = [
  {
    id: 1,
    name: "English (United Kingdom)",
    native_name: "English",
    code: "en-gb",
  },
  {
    id: 2,
    name: "French (France)",
    native_name: "Français",
    code: "fr-fr",
  },
  {
    id: 3,
    name: "Japanese",
    native_name: "日本語",
    code: "ja",
  },
  {
    id: 4,
    name: "Chinese (PRC)",
    native_name: "中文",
    code: "zh-cn",
  },
  {
    id: 5,
    name: "Welsh",
    native_name: "Cymraeg",
    code: "cy",
  },
  {
    id: 6,
    name: "Korean (South Korea)",
    native_name: "한국인",
    code: "ko-kr",
  },
  {
    id: 7,
    name: "Spanish (Spain)",
    native_name: "Español",
    code: "es-es",
  },
  {
    id: 8,
    name: "German (Germany)",
    native_name: "Deutsch",
    code: "de-de",
  },
];

export const settings: IStateSetting[] = [
  {
    id: 1,
    app_id: "swaye-website",
    site_name: "Swaye Chateau",
    url: "https://swayechateau.com",
    email: "swaye@lechateaux.com",
    location: "England, United Kingdom",
    default_lang: "en-gb",
    supported_langs: [
      "en-gb",
      "fr-fr",
      "ja",
      "de-de",
      "zh-cn",
      "cy",
      "ko-kr",
      "es-es",
    ],
    social_links: [
      {
        href: "https://github.com/swayechateau",
        icon: "fab fa-github",
      },
      {
        href: "https://github.com/swayechateau",
        icon: "fab fa-mastodon",
      },
      {
        href: "https://twitter.com/SwayeChateau",
        icon: "mdi-twitter",
      },
      {
        href: "https://www.instagram.com/swayechateau",
        icon: "mdi-instagram",
      },
      {
        href: "https://www.facebook.com/swaye.chateau",
        icon: "mdi-facebook",
      },
      {
        href: "https://www.reddit.com/user/swayec",
        icon: "mdi-reddit",
      },
      {
        href: "https://www.pinterest.co.uk/swayec/",
        icon: "mdi-pinterest",
      },
      {
        href: "https://mercylessreap.com",
        icon: "fas fa-gamepad",
      },
    ],
    founded: 2019,
    created_at: "2021-12-20T02:14:52.000000Z",
    updated_at: "2021-12-20T02:14:52.000000Z",
  },
];
export const words: IStateSitewords = {
  categories: {
    translations: {
      "en-gb": "Categories",
      "fr-fr": "Catégories",
      ja: "カテゴリー",
      "zh-cn": "类别",
      cy: "Categorïau",
      "ko-kr": "범주",
      "es-es": "Categorías",
      "de-de": "Kategorien",
    },
  },
  comments: {
    translations: {
      "en-gb": "Comments",
      "fr-fr": "Commentaires",
      ja: "コメント",
      "zh-cn": "注释",
      cy: "Sylwadau",
      "ko-kr": "코멘트",
      "es-es": "Comentarios",
      "de-de": "Kommentare",
    },
  },
  commentsDisabled: {
    translations: {
      "en-gb": "Comments Disabled",
      "fr-fr": "Commentaires Désactivé",
      ja: "コメントは無効です",
      "zh-cn": "评论已禁用",
      cy: "Sylwadau Anabl",
      "ko-kr": "댓글 비활성화",
      "es-es": "Comentarios Desactivado",
      "de-de": "Kommentare Deaktiviert",
    },
  },
  contact: {
    translations: {
      "en-gb": "Contact",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  created: {
    translations: {
      "en-gb": "Created",
      "fr-fr": "établi",
      ja: "作成した",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  dashboard: {
    translations: {
      "en-gb": "Dashboard",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  disabled: {
    translations: {
      "en-gb": "",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  enterEmail: {
    translations: {
      "en-gb": "",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  enterPassword: {
    translations: {
      "en-gb": "",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  files: {
    translations: {
      "en-gb": "Files",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  goToTop: {
    translations: {
      "en-gb": "Go To Top",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  next: {
    translations: {
      "en-gb": "Next",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  noResultsFound: {
    translations: {
      "en-gb": "No Results Found",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  of: {
    translations: {
      "en-gb": "Of",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  page: {
    translations: {
      "en-gb": "Page",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  pages: {
    translations: {
      "en-gb": "Pages",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  post: {
    translations: {
      "en-gb": "Post",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  posts: {
    translations: {
      "en-gb": "Posts",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  previous: {
    translations: {
      "en-gb": "Previous",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  project: {
    translations: {
      "en-gb": "Project",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  projects: {
    translations: {
      "en-gb": "Projects",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  publishedBy: {
    translations: {
      "en-gb": "published by",
      "fr-fr": "Publié par",
      ja: "によって公開",
      "zh-cn": "由...出版",
      cy: "Cyhoeddwyd gan",
      "ko-kr": "에 의해 출판 됨",
      "es-es": "publicado por",
      "de-de": "Veröffentlicht von",
    },
  },
  readMore: {
    translations: {
      "en-gb": "Read More",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  recent: {
    translations: {
      "en-gb": "Recent",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  recentBlogPosts: {
    translations: {
      "en-gb": "Recent Blog Posts",
      "fr-fr": "Articles de blog récents",
      ja: "最近のブログ投稿",
      "zh-cn": "最近的博文",
      cy: "Swyddi Blog Diweddar",
      "ko-kr": "최근 블로그 게시물",
      "es-es": "Entradas recientes del blog",
      "de-de": "Aktuelle Blog-Beiträge",
    },
  },
  recentPosts: {
    translations: {
      "en-gb": "Recent Posts",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  recentProjects: {
    translations: {
      "en-gb": "Recent Projects",
      "fr-fr": "les projets récents",
      ja: "最近のプロジェクト",
      "zh-cn": "最近的项目",
      cy: "Prosiectau Diweddar",
      "ko-kr": "최근 프로젝트",
      "es-es": "proyectos recientes",
      "de-de": "Letzte Projekte",
    },
  },
  recentVideos: {
    translations: {
      "en-gb": "Recent Videos",
      "fr-fr": "vidéos récentes",
      ja: "最近のビデオ",
      "zh-cn": "最近的视频",
      cy: "fideos diweddar",
      "ko-kr": "최근 동영상",
      "es-es": "Videos recientes",
      "de-de": "Aktuelle Videos",
    },
  },
  results: {
    translations: {
      "en-gb": "Results",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  resultsFor: {
    translations: {
      "en-gb": "Results For",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  search: {
    translations: {
      "en-gb": "Search",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  searchArticles: {
    translations: {
      "en-gb": "Search Articles",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  searchBlog: {
    translations: {
      "en-gb": "Search Blog",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  searchSite: {
    translations: {
      "en-gb": "Search Site",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  settings: {
    translations: {
      "en-gb": "Settings",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  subscribe: {
    translations: {
      "en-gb": "Subscribe",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  tags: {
    translations: {
      "en-gb": "Tags",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  translations: {
    translations: {
      "en-gb": "Translations",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  updated: {
    translations: {
      "en-gb": "updated",
      "fr-fr": "édité",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  users: {
    translations: {
      "en-gb": "Users",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  viewAllPosts: {
    translations: {
      "en-gb": "View All Posts",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  viewCode: {
    translations: {
      "en-gb": "View Code",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  viewDemo: {
    translations: {
      "en-gb": "View Demo",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
  vistChannel: {
    translations: {
      "en-gb": "Visit Channel",
      "fr-fr": "",
      ja: "",
      "zh-cn": "",
      cy: "",
      "ko-kr": "",
      "es-es": "",
      "de-de": "",
    },
  },
};
export const categories: IStateCategories = {
  api: {
    translations: {
      "en-gb": {
        text: "api",
        description: "",
      },
      "fr-fr": {
        text: "",
        description: "",
      },
      ja: {
        text: "",
        description: "",
      },
      "zh-cn": {
        text: "",
        description: "",
      },
      cy: {
        text: "",
        description: "",
      },
      "ko-kr": {
        text: "",
        description: "",
      },
      "es-es": {
        text: "",
        description: "",
      },
      "de-de": {
        text: "",
        description: "",
      },
    },
  },
  awesome: {
    translations: {
      "en-gb": {
        text: "awesome",
        description: "",
      },
      "fr-fr": {
        text: "impressionnant",
        description: "",
      },
      ja: {
        text: "驚くばかり",
        description: "",
      },
      "zh-cn": {
        text: "",
        description: "",
      },
      cy: {
        text: "",
        description: "",
      },
      "ko-kr": {
        text: "",
        description: "",
      },
      "es-es": {
        text: "",
        description: "",
      },
      "de-de": {
        text: "",
        description: "",
      },
    },
  },
  development: {
    translations: {
      "en-gb": {
        text: "development",
        description: "",
      },
      "fr-fr": {
        text: "développement",
        description: "",
      },
      ja: {
        text: "開発",
        description: "",
      },
      "zh-cn": {
        text: "",
        description: "",
      },
      cy: {
        text: "",
        description: "",
      },
      "ko-kr": {
        text: "",
        description: "",
      },
      "es-es": {
        text: "",
        description: "",
      },
      "de-de": {
        text: "",
        description: "",
      },
    },
  },
  laravel: {
    translations: {
      "en-gb": {
        text: "laravel",
        description: "",
      },
      "fr-fr": {
        text: "",
        description: "",
      },
      ja: {
        text: "",
        description: "",
      },
      "zh-cn": {
        text: "",
        description: "",
      },
      cy: {
        text: "",
        description: "",
      },
      "ko-kr": {
        text: "",
        description: "",
      },
      "es-es": {
        text: "",
        description: "",
      },
      "de-de": {
        text: "",
        description: "",
      },
    },
  },
  leisure: {
    translations: {
      "en-gb": {
        text: "leisure",
        description: "",
      },
      "fr-fr": {
        text: "loisir",
        description: "",
      },
      ja: {
        text: "余暇",
        description: "",
      },
      "zh-cn": {
        text: "",
        description: "",
      },
      cy: {
        text: "",
        description: "",
      },
      "ko-kr": {
        text: "",
        description: "",
      },
      "es-es": {
        text: "",
        description: "",
      },
      "de-de": {
        text: "",
        description: "",
      },
    },
  },
  lumen: {
    translations: {
      "en-gb": {
        text: "lumen",
        description: "",
      },
      "fr-fr": {
        text: "",
        description: "",
      },
      ja: {
        text: "",
        description: "",
      },
      "zh-cn": {
        text: "",
        description: "",
      },
      cy: {
        text: "",
        description: "",
      },
      "ko-kr": {
        text: "",
        description: "",
      },
      "es-es": {
        text: "",
        description: "",
      },
      "de-de": {
        text: "",
        description: "",
      },
    },
  },
  photography: {
    translations: {
      "en-gb": {
        text: "photography",
        description: "",
      },
      "fr-fr": {
        text: "la photographie",
        description: "",
      },
      ja: {
        text: "写真撮影",
        description: "",
      },
      "zh-cn": {
        text: "摄影",
        description: "",
      },
      cy: {
        text: "ffotograffiaeth",
        description: "",
      },
      "ko-kr": {
        text: "사진술",
        description: "",
      },
      "es-es": {
        text: "fotografía",
        description: "",
      },
      "de-de": {
        text: "fotografie",
        description: "",
      },
    },
  },
  php: {
    translations: {
      "en-gb": {
        text: "php",
        description: "",
      },
      "fr-fr": {
        text: "",
        description: "",
      },
      ja: {
        text: "",
        description: "",
      },
      "zh-cn": {
        text: "",
        description: "",
      },
      cy: {
        text: "",
        description: "",
      },
      "ko-kr": {
        text: "",
        description: "",
      },
      "es-es": {
        text: "",
        description: "",
      },
      "de-de": {
        text: "",
        description: "",
      },
    },
  },
  react: {
    translations: {
      "en-gb": {
        text: "reactjs",
        description: "",
      },
      "fr-fr": {
        text: "",
        description: "",
      },
      ja: {
        text: "",
        description: "",
      },
      "zh-cn": {
        text: "",
        description: "",
      },
      cy: {
        text: "",
        description: "",
      },
      "ko-kr": {
        text: "",
        description: "",
      },
      "es-es": {
        text: "",
        description: "",
      },
      "de-de": {
        text: "",
        description: "",
      },
    },
  },
  "react-native": {
    translations: {
      "en-gb": {
        text: "react native",
        description: "",
      },
      "fr-fr": {
        text: "",
        description: "",
      },
      ja: {
        text: "",
        description: "",
      },
      "zh-cn": {
        text: "",
        description: "",
      },
      cy: {
        text: "",
        description: "",
      },
      "ko-kr": {
        text: "",
        description: "",
      },
      "es-es": {
        text: "",
        description: "",
      },
      "de-de": {
        text: "",
        description: "",
      },
    },
  },
  sample: {
    translations: {
      "en-gb": {
        text: "sample",
        description: "",
      },
      "fr-fr": {
        text: "",
        description: "",
      },
      ja: {
        text: "",
        description: "",
      },
      "zh-cn": {
        text: "",
        description: "",
      },
      cy: {
        text: "",
        description: "",
      },
      "ko-kr": {
        text: "",
        description: "",
      },
      "es-es": {
        text: "",
        description: "",
      },
      "de-de": {
        text: "",
        description: "",
      },
    },
  },
  test: {
    translations: {
      "en-gb": {
        text: "test",
        description: "",
      },
      "fr-fr": {
        text: "tester",
        description: "",
      },
      ja: {
        text: "",
        description: "",
      },
      "zh-cn": {
        text: "",
        description: "",
      },
      cy: {
        text: "",
        description: "",
      },
      "ko-kr": {
        text: "",
        description: "",
      },
      "es-es": {
        text: "",
        description: "",
      },
      "de-de": {
        text: "",
        description: "",
      },
    },
  },
  travel: {
    translations: {
      "en-gb": {
        text: "travel",
        description: "",
      },
      "fr-fr": {
        text: "voyage",
        description: "",
      },
      ja: {
        text: "旅行",
        description: "",
      },
      "zh-cn": {
        text: "",
        description: "",
      },
      cy: {
        text: "",
        description: "",
      },
      "ko-kr": {
        text: "",
        description: "",
      },
      "es-es": {
        text: "",
        description: "",
      },
      "de-de": {
        text: "",
        description: "",
      },
    },
  },
  vue: {
    translations: {
      "en-gb": {
        text: "vue",
        description: "",
      },
      "fr-fr": {
        text: "",
        description: "",
      },
      ja: {
        text: "",
        description: "",
      },
      "zh-cn": {
        text: "",
        description: "",
      },
      cy: {
        text: "",
        description: "",
      },
      "ko-kr": {
        text: "",
        description: "",
      },
      "es-es": {
        text: "",
        description: "",
      },
      "de-de": {
        text: "",
        description: "",
      },
    },
  },
  web: {
    translations: {
      "en-gb": {
        text: "Website",
        description: "",
      },
      "fr-fr": {
        text: "",
        description: "",
      },
      ja: {
        text: "",
        description: "",
      },
      "zh-cn": {
        text: "",
        description: "",
      },
      cy: {
        text: "",
        description: "",
      },
      "ko-kr": {
        text: "",
        description: "",
      },
      "es-es": {
        text: "",
        description: "",
      },
      "de-de": {
        text: "",
        description: "",
      },
    },
  },
};
export const pages: IStatePages = {
  "401": {
    published: 0,
    index: "error401",
    hero: "https://swayechateau.com/media/image/lost-city.jpg",
    slug: "/401",
    posted_at: null,
    translations: {
      "en-gb": {
        page_id: 13,
        name: "401",
        title: "Whoops, 401!",
        sub_title: "Seems, You Are Lost Traveller!",
        description: null,
        content: {
          return: "Show me the way!",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      "fr-fr": {
        page_id: 13,
        name: "401",
        title: "Oups, 401!",
        sub_title: "Semble, vous êtes perdu voyageur!",
        description: null,
        content: {
          return: "montre moi le chemin!",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      ja: {
        page_id: 13,
        name: "401",
        title: "おっと 401",
        sub_title: "旅行者、あなたは失われました",
        description: null,
        content: {
          return: "道を示す",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  "404": {
    published: 0,
    index: "error404",
    hero: "https://swayechateau.com/media/image/lost-city.jpg",
    slug: "/404",
    posted_at: null,
    translations: {
      "en-gb": {
        page_id: 11,
        name: "404",
        title: "Whoops, 404!",
        sub_title: "Seems, You Are Lost Traveller!",
        description: null,
        content: {
          return: "Show me the way!",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      "fr-fr": {
        page_id: 11,
        name: "404",
        title: "Oups, 404!",
        sub_title: "Semble, vous êtes perdu voyageur!",
        description: null,
        content: {
          return: "montre moi le chemin!",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      ja: {
        page_id: 11,
        name: "404",
        title: "おっと 404",
        sub_title: "旅行者、あなたは失われました",
        description: null,
        content: {
          return: "道を示す",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  "408": {
    published: 0,
    index: "error408",
    hero: "https://swayechateau.com/media/image/lost-city.jpg",
    slug: "/408",
    posted_at: null,
    translations: {
      "en-gb": {
        page_id: 12,
        name: "408",
        title: "Whoops, 408!",
        sub_title: "Seems, You Are Lost Traveller!",
        description: null,
        content: {
          return: "Show me the way!",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      "fr-fr": {
        page_id: 12,
        name: "408",
        title: "Oups, 408!",
        sub_title: "Semble, vous êtes perdu voyageur!",
        description: null,
        content: {
          return: "montre moi le chemin!",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      ja: {
        page_id: 12,
        name: "408",
        title: "おっと 408",
        sub_title: "旅行者、あなたは失われました",
        description: null,
        content: {
          return: "道を示す",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  home: {
    published: 0,
    index: "home",
    hero: "https://swayechateau.com/media/image/deep-blue.jpg", //https://file.swayechateau.com/view/swayechateauZJpQjF4EPOj0MVC1e0t223
    slug: "/",
    posted_at: null,
    translations: {
      "en-gb": {
        page_id: 1,
        name: "Home",
        title: "Welcome to my world!", //I am Swaye Chateau
        sub_title: "Photographer / Vlogger / Software Engineer / Investor",
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:08.000000Z",
      },
      "fr-fr": {
        page_id: 1,
        name: "Accueil",
        title: "Bienvenue dans mon monde!",
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:08.000000Z",
      },
      ja: {
        page_id: 1,
        name: "ホーム",
        title: "私の世界へようこそ",
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:08.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  about: {
    published: 0,
    index: "about",
    hero: "https://swayechateau.com/media/image/aboutme.png",
    slug: "/about-me",
    posted_at: null,
    translations: {
      "en-gb": {
        page_id: 2,
        name: "About",
        title: "About Me",
        sub_title: "Coding One Day At a Time!",
        description: null,
        content: {
          name: "Swaye Chateau",
          about:
            "<p>Hello, Swaye here. I am a software developer, who likes to learn and build things, I am currently learning animation and Mandarin. My passion for tech and knowledge is what drives me to constantly want to learn new things and the latest creations out there!!</p><p>Being an open individual, I have tailored my site to reflect who I am, you could say this site is my life journal and toy box. I have not invested time into building this site for anyone in particular, unless you know me or are trying to get to know, then welcome to my world!!!</p><p>P.S. For those that don't know me, I can be a tad socially awkward... Or maybe more than a tad, I will let you decide that! :p</p>",
          skills: {
            title: "Skills <span class='grey--text'>(To Pay The Bills)</span>",
            intro:
              "If you are on my site to assess my skills for work, my CV can be found here: <a href='https://cv.swayechateau.com' target='_blank'>Curriculum Vitae</a>",
          },
          status: "Coding One Day At a Time.",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      "fr-fr": {
        page_id: 2,
        name: "Sur",
        title: "À propos de moi",
        sub_title: "coder un jour à la fois",
        description: null,
        content: {
          name: "Château de Swaye",
          about:
            "<p>Bonjour, Swaye ici. Je suis un développeur de logiciels, qui aime apprendre et construire des choses, j'apprends actuellement l'animation et le mandarin. Ma passion pour la technologie et le savoir me pousse à vouloir constamment apprendre de nouvelles choses et les dernières créations!</p><p>Étant un individu ouvert, j'ai adapté mon site pour refléter qui je suis, on pourrait dire que ce site est mon journal de vie et mon coffre à jouets. Je n'ai pas investi de temps dans la construction de ce site pour quelqu'un en particulier, à moins que vous ne me connaissiez ou que vous n'essayiez de vous connaître, alors bienvenue dans mon monde !!!</p><p>P.S. Pour ceux qui ne me connaissent pas, je peux être un peu maladroit socialement ... Ou peut-être plus qu'un peu, je vous laisse décider! :p</p>",
          skills: {
            title:
              "Compétences <span class='grey--text'>(Payer les factures)</span>",
            intro:
              "Si vous êtes sur mon site pour évaluer mes compétences professionnelles, mon CV se trouve ici: <a href='https://cv.swayechateau.com' target='_blank'>Curriculum Vitae</a>",
          },
          status: "À propos de moi",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      ja: {
        page_id: 2,
        name: "約",
        title: "私について",
        sub_title: "1日1回プログラミング",
        description: null,
        content: {
          name: "シャトー・スウェイ",
          about:
            "<p>こんにちは、スウェイ です。私はソフトウェア開発者であり、物事を学び構築するのが好きで、現在アニメーションと標準中国語を学んでいます。技術と知識に対する私の情熱は、常に新しいことやそこにある最新の作品を学びたいと思うように駆り立てるものです</p><p>オープンな個人であるため、私は自分が誰であるかを反映するようにサイトを調整しました。このサイトは私の人生日記であり、おもちゃ箱です。あなたが私を知っているか、知りたがっていない限り、私はこのサイトを特に誰かのために構築することに時間を費やしていません。</p><p>私を知らない人、私は少し社会的に厄介なことができます。</p>",
          skills: {
            title: "スキル <span class='grey--text'>(手形を支払う)</span>",
            intro:
              "仕事のためのスキルを評価するために私のサイトにいる場合、私の履歴書はここで見つけることができます <a href='https://cv.swayechateau.com' target='_blank'>履歴書</a>",
          },
          status: "1日1回プログラミング",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  projects: {
    published: 0,
    index: "projects",
    hero: "https://swayechateau.com/media/image/futaba-computer.jpg",
    slug: "/projects",
    posted_at: null,
    translations: {
      "en-gb": {
        page_id: 3,
        name: "Projects",
        title: "Projects!!!!!!",
        sub_title: "Assortments of projects",
        description: null,
        content: {
          menu: ["All", "Open Source", "Closed Source"],
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      "fr-fr": {
        page_id: 3,
        name: "Projets",
        title: "Projets!!!!",
        sub_title: "Assortiments de projets",
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      ja: {
        page_id: 3,
        name: "プロジェクト",
        title: "プロジェクト!!!",
        sub_title: "プロジェクトの品揃え",
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  blog: {
    published: 0,
    index: "blog",
    hero: "https://swayechateau.com/media/image/anime-girl-futuristic-city-computer-short-hair-coffee-25464.jpeg",
    slug: "/blog",
    posted_at: null,
    translations: {
      "en-gb": {
        page_id: 4,
        name: "Blog",
        title: "The Life Of Swaye",
        sub_title: "Etching my journey, One post at a time",
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      "fr-fr": {
        page_id: 4,
        name: "Blog",
        title: "L'art du voyage",
        sub_title: "Trouver la beauté, un vol à la fois",
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      ja: {
        page_id: 4,
        name: "ブログ",
        title: "旅行の芸術",
        sub_title: "美を見つける、一度に1つのフライト",
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  "blog-categories": {
    published: 0,
    index: "blog-categories",
    hero: "https://swayechateau.com/media/image/anime-girl-futuristic-city-computer-short-hair-coffee-25464.jpeg",
    slug: "/blog/categories",
    posted_at: null,
    translations: {
      "en-gb": {
        page_id: 5,
        name: "Categories",
        title: "The Life Of Swaye",
        sub_title: "Etching my journey, One post at a time",
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      "fr-fr": {
        page_id: 5,
        name: "Blog",
        title: "L'art du voyage",
        sub_title: "Trouver la beauté, un vol à la fois",
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      ja: {
        page_id: 5,
        name: "ブログ",
        title: "旅行の芸術",
        sub_title: "美を見つける、一度に1つのフライト",
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  videos: {
    published: 0,
    index: "videos",
    hero: "https://swayechateau.com/media/image/anime-girl-futuristic-city-computer-short-hair-coffee-25464.jpeg",
    slug: "/videos",
    posted_at: null,
    translations: {
      "en-gb": {
        page_id: 6,
        name: "Videos",
        title: "The Life Of Swaye",
        sub_title: "Etching my journey, One post at a time",
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      "fr-fr": {
        page_id: 6,
        name: "Blog",
        title: "L'art du voyage",
        sub_title: "Trouver la beauté, un vol à la fois",
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      ja: {
        page_id: 6,
        name: "ブログ",
        title: "旅行の芸術",
        sub_title: "美を見つける、一度に1つのフライト",
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  course: {
    published: 0,
    index: "course",
    hero: "https://swayechateau.com/media/image/anime-girl-futuristic-city-computer-short-hair-coffee-25464.jpeg",
    slug: "/courses",
    posted_at: null,
    translations: {
      "en-gb": {
        page_id: 7,
        name: "Courses",
        title: "The Life Of Swaye",
        sub_title: "Etching my journey, One post at a time",
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      "fr-fr": {
        page_id: 7,
        name: "Blog",
        title: "L'art du voyage",
        sub_title: "Trouver la beauté, un vol à la fois",
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      ja: {
        page_id: 7,
        name: "ブログ",
        title: "旅行の芸術",
        sub_title: "美を見つける、一度に1つのフライト",
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  login: {
    published: 0,
    index: "login",
    hero: "https://swayechateau.com/media/image/kaneki.jpg",
    slug: "/login",
    posted_at: null,
    translations: {
      "en-gb": {
        page_id: 8,
        name: "Login",
        title: "Login Into This App",
        sub_title: null,
        description: null,
        content: {
          email: "Email Address",
          submit: "Login",
          password: "Password",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      "fr-fr": {
        page_id: 8,
        name: "S'identifier",
        title: "Connectez-vous à cette application",
        sub_title: null,
        description: null,
        content: {
          email: "Adresse e-mail",
          submit: "S'identifier",
          password: "Mot de passe",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      ja: {
        page_id: 8,
        name: "ログインする",
        title: "このアプリにログインしてください",
        sub_title: null,
        description: null,
        content: {
          email: "電子メールアドレス",
          submit: "ログインする",
          password: "パスワード",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:09.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  downloads: {
    published: 0,
    index: "downloads",
    hero: "https://swayechateau.com/media/image/kaneki.jpg",
    slug: "/downloads",
    posted_at: null,
    translations: {
      "en-gb": {
        page_id: 9,
        name: "Downloads",
        title: "Downloads",
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      "fr-fr": {
        page_id: 9,
        name: "Downloads",
        title: "Downloads",
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      ja: {
        page_id: 9,
        name: "ダウンロード",
        title: "ダウンロード",
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  "curriculum-vitae": {
    published: 0,
    index: "curriculum-vitae",
    hero: "",
    slug: "/curriculum-vitae",
    posted_at: null,
    translations: {
      "en-gb": {
        page_id: 10,
        name: "Curriculum Vitae",
        title: null,
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      "fr-fr": {
        page_id: 10,
        name: "Curriculum Vitae",
        title: null,
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      ja: {
        page_id: 10,
        name: "履歴書",
        title: null,
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  "505": {
    published: 0,
    index: "error505",
    hero: "https://swayechateau.com/media/image/lost-city.jpg",
    slug: "/505",
    posted_at: null,
    translations: {
      "en-gb": {
        page_id: 14,
        name: "505",
        title: "Whoops, 505!",
        sub_title: "Seems, You Are Lost Traveller!",
        description: null,
        content: {
          return: "Show me the way!",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      "fr-fr": {
        page_id: 14,
        name: "505",
        title: "Oups, 505!",
        sub_title: "Semble, vous êtes perdu voyageur!",
        description: null,
        content: {
          return: "montre moi le chemin!",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      ja: {
        page_id: 14,
        name: "505",
        title: "おっと 505",
        sub_title: "旅行者、あなたは失われました",
        description: null,
        content: {
          return: "道を示す",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  dashboard: {
    published: 0,
    index: "dashboard",
    hero: null,
    slug: "/dashboard",
    posted_at: null,
    translations: {
      "en-gb": {
        page_id: 15,
        name: "Dashboard",
        title: "Dashboard",
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      "fr-fr": {
        page_id: 15,
        name: "portail",
        title: "portail",
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      ja: {
        page_id: 15,
        name: "ダッシュボード",
        title: "ダッシュボード",
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  posts: {
    published: 0,
    index: "posts",
    hero: null,
    slug: "/blog/posts",
    posted_at: null,
    translations: {
      "en-gb": {
        page_id: 16,
        name: "posts",
        title: "Posts",
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      "fr-fr": {
        page_id: 16,
        name: "portail",
        title: "portail",
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      ja: {
        page_id: 16,
        name: "ダッシュボード",
        title: "ダッシュボード",
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:10.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
};
export const posts: IStatePosts = {
  "b-&-q-photo-day-12-21": {
    index: "b-&-q-photo-day-12-21",
    published: 1,
    featured: 0,
    prominent: 1,
    category: "photography",
    name: null,
    hero: "https://images.unsplash.com/photo-1639930940899-7f6d1661bcb8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    slug: "/blog/posts/b-&-q-photo-day-12-21",
    posted_at: "2021-12-19 14:58:54",
    translations: {
      "en-gb": {
        short_name: null,
        title: "B&Q Photo Day",
        sub_title: null,
        description: null,
        content: {
          body: "<img src='https://cdn.vuetifyjs.com/images/cards/cooking.png'/><hr/><iframe width='100%' height='340vh' src='https://www.youtube-nocookie.com/embed/afcKMij2E3g' frameborder='0' allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
        },
        aside: 1,
        meta: null,
        updated_at: "2021-12-20T02:15:12.000000Z",
        readtime: 1,
      },
      "fr-fr": {
        short_name: null,
        title: "Journée photo B&Q",
        sub_title: null,
        description: null,
        content: {
          body: "<img src='https://cdn.vuetifyjs.com/images/cards/cooking.png'/><hr/><iframe width='100%' height='340vh' src='https://www.youtube-nocookie.com/embed/afcKMij2E3g' frameborder='0' allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
        },
        aside: 1,
        meta: null,
        updated_at: "2021-12-20T02:15:12.000000Z",
        readtime: 1,
      },
      ja: {
        short_name: null,
        title: "B＆Qフォトデー",
        sub_title: null,
        description: null,
        content: {
          body: "<img src='https://cdn.vuetifyjs.com/images/cards/cooking.png'/><hr/><iframe width='100%' height='340vh' src='https://www.youtube-nocookie.com/embed/afcKMij2E3g' frameborder='0' allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
        },
        aside: 1,
        meta: null,
        updated_at: "2021-12-20T02:15:12.000000Z",
        readtime: 1,
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  "new-year-new-decade-2020": {
    index: "new-year-new-decade-2020",
    published: 1,
    featured: 1,
    prominent: 0,
    category: "awesome",
    name: null,
    hero: "https://images.unsplash.com/photo-1639930827554-fa7ff66ce343?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80",
    slug: "/blog/posts/new-year-new-decade-2020",
    posted_at: "2020-01-01 07:54:35",
    translations: {
      "en-gb": {
        short_name: null,
        title: "New Year, New Decade 2020",
        sub_title: null,
        description: null,
        content: {
          body: "<h2>What is Lorem Ipsum?</h2><p><strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p><h2>Why do we use it?</h2><p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p><br><h2>Where does it come from</h2><p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of 'de Finibus Bonorum et Malorum' (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, 'Lorem ipsum dolor sit amet..', comes from a line in section 1.10.32.</p><p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from 'de Finibus Bonorum et Malorum' by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p><h2>Where can I get some?</h2><p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to geneate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</p>",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:11.000000Z",
        readtime: 3,
      },
      "fr-fr": {
        short_name: null,
        title: "Nouvelle Année, Nouvelle Décennie 2020",
        sub_title: null,
        description: null,
        content: {
          body: "<p>Lorem superposés valise pourparlers rêver chiots rendez-vous naissance Eiffel myrtille. Grèves Arc de Triomphe encore pourquoi sentiments baguette pédiluve une projet sentiments saperlipopette vachement le. Brume éphémère baguette Bordeaux en fait sommet avoir minitel.</p><p>Nous avoir parole la nous moussant. Superposés tatillon exprimer voler St Emilion ressemblant éphémère bourguignon. Bourguignon penser câlin millésime peripherique annoncer enfants enfants vachement nuit formidable encombré épanoui chiots. Arc truc cacatoès lorem flâner.</p>",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:11.000000Z",
        readtime: 1,
      },
      ja: {
        short_name: null,
        title: "2020年新年",
        sub_title: null,
        description: null,
        content: {
          body: "<p>しかし私は、喜びを非難して苦痛を賞賛するという誤ったこの考えがすべてどのようにして誕生したかをあなたに説明しなければならないから、私はあなたにその体系を完璧に説明し、真実を求める偉大な探究家、人間の喜びを築く建築家の実践的な教えを詳しく説明しよう。だれも喜びそのものを、それが喜びであるという理由で拒んだり、嫌ったり、避けたりはしない。しかし、どのようにして喜びを理性的に追求するかを知らない人たちは非常に苦痛な結末に直面する。同様に、苦痛そのものを、それが苦痛であるという理由で愛したり、探したり、手に入れることを望んだりする者もいない。しかし、ときには苦労や苦痛がその人に大いなる喜びをいくらかもたらす状況がおこることがある。些末な例を挙げると、私たちのうちのだれが、そこから何か有益なものを得られないのに、骨の折れる肉体運動を引き受けるだろうか？しかしだれに、いらだたしい結末のない喜びを享受することを選ぶ人や、その結果としての喜びを生み出さないような痛みを避ける人にある、落ち度を見つける権利はあるのだろうか？</p><p>一方、わたしたちは正当な憤りをもって批判する。そして、今の喜びの魅力にだまされてあまりにもやる気を失い、欲望によってあまりにも盲目的になってしまうことで、その後に起こるべき苦痛や困難を予想できなくなってしまう人たちを嫌う；そして、同等の非難は意志の弱さによって自身の務めに失敗する人たちにも当てはまる。これは苦労から苦痛へと縮小することと等しい。これらの場合は完全に単純で、見分けるのはたやすい。自由なときにおいて、選択の力に制約がなく、いちばん好きなものを選ぶのに一切の妨げがないとき、あらゆる喜びが受け入れられ、あらゆる苦痛が避けられる。しかし、ある特定の状況において務めや義務により、しばしば喜びを拒み、いらだたしいことを受け入れなければならないことが起こる。賢い人間はそれゆえ常に、この選択の原則によってこれらの問題を制する：賢い人間は他のより大きな喜びを確実に手に入れるためならば喜びを拒み、あるいはよりひどいものを避けるために苦痛に耐え、長生きをし、縁起の良いことをするのである。</p>",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:11.000000Z",
        readtime: 1,
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  "the-adventure-begins": {
    index: "the-adventure-begins",
    published: 1,
    featured: 0,
    prominent: 1,
    category: "awesome",
    name: null,
    hero: "https://images.unsplash.com/photo-1640175951336-41d45843b3db?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80",
    slug: "/blog/posts/the-adventure-begins",
    posted_at: "2019-10-24 17:00:05",
    translations: {
      "en-gb": {
        short_name: null,
        title: "The Adventure Begins",
        sub_title: null,
        description: null,
        content: {
          body: "<iframe width='100%' height='340vh' src='https://www.youtube.com/embed/zF5Ddo9JdpY' allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:11.000000Z",
        readtime: 1,
      },
      "fr-fr": {
        short_name: null,
        title: "L'aventure commence",
        sub_title: null,
        description: null,
        content: {
          body: "<iframe width='100%' height='340vh' src='https://www.youtube.com/embed/zF5Ddo9JdpY' allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:11.000000Z",
        readtime: 1,
      },
      ja: {
        short_name: null,
        title: "冒険の始まり",
        sub_title: null,
        description: null,
        content: {
          body: "<iframe width='100%' height='340vh' src='https://www.youtube.com/embed/zF5Ddo9JdpY' allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:11.000000Z",
        readtime: 1,
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  "time-to-rise": {
    index: "time-to-rise",
    published: 1,
    featured: 1,
    prominent: 0,
    category: "leisure",
    name: null,
    hero: "https://images.unsplash.com/photo-1640176701536-c62dfe7a513f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwcm9maWxlLXBhZ2V8M3x8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60",
    slug: "/blog/posts/time-to-rise",
    posted_at: "2019-10-24 16:35:50",
    translations: {
      "en-gb": {
        short_name: null,
        title: "Time To Rise",
        sub_title: null,
        description: null,
        content: {
          body: "<iframe width='100%' height='340vh' src='https://www.youtube.com/embed/fB8TyLTD7EE' frameborder='0' allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:11.000000Z",
        readtime: 1,
      },
      "fr-fr": {
        short_name: null,
        title: "Time To Rise",
        sub_title: null,
        description: null,
        content: {
          body: "<iframe width='100%' height='340vh' src='https://www.youtube.com/embed/fB8TyLTD7EE' frameborder='0' allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:11.000000Z",
        readtime: 1,
      },
      ja: {
        short_name: null,
        title: "立ち上がりまでの時間",
        sub_title: null,
        description: null,
        content: {
          body: "<iframe width='100%' height='340vh' src='https://www.youtube.com/embed/fB8TyLTD7EE' frameborder='0' allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:11.000000Z",
        readtime: 1,
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
  "moroccan-day": {
    index: "moroccan-day",
    published: 1,
    featured: 1,
    prominent: 0,
    category: "travel",
    name: null,
    hero: "https://images.unsplash.com/photo-1640176706316-3678dc755661?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    slug: "/blog/posts/moroccan-day",
    posted_at: "2019-10-24 04:58:54",
    translations: {
      "en-gb": {
        short_name: null,
        title: "Moroccan Day",
        sub_title: null,
        description: null,
        content: {
          body: "<video controls><source src='https://file.swayechateau.com/view/globalL4QZkdkYePZErybxFTXN3'></video>",
        },
        aside: 1,
        meta: null,
        updated_at: "2021-12-20T02:15:11.000000Z",
        readtime: 1,
      },
      "fr-fr": {
        short_name: null,
        title: "Jour Marocain",
        sub_title: null,
        description: null,
        content: {
          body: "<img src='https://cdn.vuetifyjs.com/images/cards/cooking.png'/><hr/><iframe width='100%' height='340vh' src='https://www.youtube-nocookie.com/embed/afcKMij2E3g' frameborder='0' allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
        },
        aside: 1,
        meta: null,
        updated_at: "2021-12-20T02:15:11.000000Z",
        readtime: 1,
      },
      ja: {
        short_name: null,
        title: "モロッコの日",
        sub_title: null,
        description: null,
        content: {
          body: "<img src='https://cdn.vuetifyjs.com/images/cards/cooking.png'/><hr/><iframe width='100%' height='340vh' src='https://www.youtube-nocookie.com/embed/afcKMij2E3g' frameborder='0' allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>",
        },
        aside: 1,
        meta: null,
        updated_at: "2021-12-20T02:15:11.000000Z",
        readtime: 1,
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
  },
};

export const projects: IStateProjects = {
  "movie-list": {
    published: 1,
    open_source: 1,
    hero: "https://swayechateau.com/media/image/projects/movie-list-search.jpg",
    slug: "/projects?p=movie-list",
    git_url: "https://github.com/swayechateau/react-movie-list",
    demo_url: "https://ml.swayechateau.com",
    posted_at: null,
    translations: {
      "en-gb": {
        name: "Movie List",
        title: "Recruitment Project Movie list",
        sub_title: null,
        description: "A simple react frontend for the OMDb API",
        content: {
          body: "Built with React and vanilla css, I chose to complete this project after failing an interview. I saw it as a good oportunity to go over the basics and brush up on popular frameworks.",
        },
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:12.000000Z",
      },
      "fr-fr": {
        name: "Liste de Film",
        title: null,
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:12.000000Z",
      },
      ja: {
        name: "映画リスト",
        title: null,
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:12.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
    tags: ["react", "web"],
  },
  "file-server": {
    published: 1,
    open_source: 1,
    hero: "https://file.swayechateau.com/view/globaliyndTnSCK14onpASVq7n5?share_code=s5LUL0lAdDLS",
    slug: "/projects?p=file-server",
    git_url: "https://github.com/swayechateau/fileserver",
    demo_url: "https://file.swayechateau.com",
    posted_at: null,
    translations: {
      "en-gb": {
        name: "File Server",
        title: null,
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:13.000000Z",
      },
      "fr-fr": {
        name: "File Server",
        title: null,
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:13.000000Z",
      },
      ja: {
        name: "File Server",
        title: null,
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:13.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
    tags: ["lumen", "php"],
  },
  "web-meta-grabber": {
    published: 1,
    open_source: 1,
    hero: "https://file.swayechateau.com/view/globalMaJKf2UDzFdqba7hG96U6?share_code=s6LHjQlIsFHc",
    slug: "/projects?p=web-meta-grabber",
    git_url: "https://github.com/swayechateau/web-meta-grabber",
    demo_url: "https://meta.swayechateau.com",
    posted_at: null,
    translations: {
      "en-gb": {
        name: "Web Meta Grabber",
        title: null,
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:13.000000Z",
      },
      "fr-fr": {
        name: "Web Meta Grabber",
        title: null,
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:13.000000Z",
      },
      ja: {
        name: "Web Meta Grabber",
        title: null,
        sub_title: null,
        description: null,
        content: null,
        aside: 0,
        meta: null,
        updated_at: "2021-12-20T02:15:13.000000Z",
      },
      "zh-cn": null,
      cy: null,
      "ko-kr": null,
      "es-es": null,
      "de-de": null,
    },
    tags: ["lumen", "php"],
  },
};
